word_list = {
    'nigger': 'XD', 'kys': 'XD', 'fucking': 'XD',
    'dog': 'XD','fuckign':'XD','cancer':'candy',
    'retard':'XD','retarded':'XD','ky5':'XD',
    'shit':'XD','niger':'XD','nyger':'XD',
    'ky$':'XD','blackskin':'XD','black':'XD',
    'tumor':'XD','tumour':'XD','kill':'XD',
    'childs':'XD','rape':'XD','dogshit':'XD',
    'cancr':'XD','cacner':'XD','cncr':'XD',
    'syk':'XD','faking':'XD','fakin':'XD',
    'rapist':'XD','raping':'XD','sucking':'XD',
    'raper':'XD','cancerlow':'XD','braindead':'XD',
    'braindamaged':'XD','damaged':'XD','dmged':'XD',
    'brindead':'XD','brauindead':'XD','brainded':'XD',
    'braindamaged':'XD','damaged':'XD','dmged':'XD',
    'nggygier':'XD','nygier':'XD','ngier':'XD',
    'igger':'XD','ygger':'XD','n4ygger':'XD',
    'nigeer':'XD','niggerr':'XD','nigeerr':'XD',
    'niigger':'XD','niiger':'XD','niigeer':'XD',
    'nyga':'XD','nyggaa':'nygg','':'','':'',
    '':'','':'','':'','':'',
    '':'','':'','':'','':'',
    '':'','':'','':'','':'',
    '':'','':'','':'','':'',
    '':'','':'','':'','':'',
    '':'','':'','':'','':'',
}